plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "a.rb"
    - "vendor/**/*"
    - "bin/benchmark"
    - "bin/profile"
    - "tmp/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/AccessModifierDeclarations:
  EnforcedStyle: inline

Naming/FileName:
  Enabled: false

Layout/LineLength:
  Max: 160

Lint/DuplicateBranch:
  Enabled: false

Style/NegatedIf:
  Enabled: false

# LiteralNode.values is an Array, not a Hash
Style/HashEachMethods:
  Enabled: false

# Disable all Metrics cops
Metrics:
  Enabled: false

# RSpec cops configuration
RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/ruby_lsp/addon_loading_spec.rb"
    - "spec/ruby_lsp/independent_addon_loading_spec.rb"

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false
