development:
  clients:
    default:
      database: type_guessr_mongoid_dev
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1

test:
  clients:
    default:
      database: type_guessr_mongoid_test
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
